@startuml
'https://plantuml.com/class-diagram

class App{
    main()
    start()
}

class SceneManager{
    -scenes: Map<String, Scene>

    +loadScenes()
    +getScene(String): Scene
}

class InventoryController{
    model: Inventory
    scene: SceneManager
    fileManager: FileManager
    fileChooser: FileChooser

    'add item btn
    +addItemBtnClicked(ActionEvent event)
    'remove item btn
    +removeItemBtnClicked(ActionEvent event)
    'search btn
    +searchBtnClicked(ActionEvent event)

    'edit table
    +edit(ActionEvent event)

    'file manager functions
    +saveAsClicked(ActionEvent event)
    +loadClicked(ActionEvent event)



}

class AddItemController{
    model: Inventory
    scene: SceneManager

    'add item btn
    +addItemBtnClicked(ActionEvent event)
}

class Inventory{
    -items: ObservableList<Item>

    'constructor
    +Inventory()
    'getter
    +getItems(): ObservableList<Item>
    'setter
    +setItems(ObservableList<Item>

}

class Item{
    'private instance variables
    -name: SimpleStringProperty
    -serial: SimpleStringProperty
    -value: SimpleDoubleProperty

    'constructor
    +Item(String, String, Double)

    'getters
    +getName(): String
    +getSerial(): String
    +getValue(): double

    'setters
    +setName(String)
    +setSerial(String)
    +setValue(double)
}

class FileManager{
    'constructor
    +FileManager()

    'save
    +saveAsTSV(File, Inventory)
    +saveAsHTML(File, Inventory)
    +saveAsJSON(File, Inventory)

    'load
    +loadTSV(File): Inventory
    +loadHTML(File): Inventory
    +loadJSON(File): Inventory
}

org.javafx.Application <|- App
App -- SceneManager
SceneManager -- InventoryController
InventoryController -- FileManager
SceneManager -- AddItemController
InventoryController *-> Inventory
AddItemController *--> Inventory
Inventory *--> Item

@enduml