@startuml
'https://plantuml.com/class-diagram

class App{
    main()
    start()
}

class Controller{
    model: Inventory
    obList: ObservableList<Item>
    fileChooser: FileChooser


}

class Inventory{
    -items: ArrayList<Item>

    'constructor
    +Inventory()

}

class Item{
    'private instance variables
    -name: SimpleStringProperty
    -serial: SimpleStringProperty
    -value: double

    'constructor
    +Item(String, String, Double)

    'getters
    +getName(): String
    +getSerial(): String
    +getValue(): double

    'setters
    +setName(String)
    +setSerial(String)
    +setValue(double)
}

org.javafx.Application <|- App
App -- Controller
Controller *-> Inventory
Inventory *--> Item

@enduml